import type { Env, CitedBriefing } from "./types.js";

export type StoredBriefing = {
  id: string;
  ts: number;
  question: string;
  briefing: CitedBriefing;
};

const KEY_PREFIX = "briefing:";
const TTL_SECONDS = 60 * 60 * 24 * 90; // 90 days

export function newBriefingId(): string {
  const bytes = new Uint8Array(6);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => b.toString(36).padStart(2, "0")).join("").slice(0, 10);
}

export async function saveBriefing(
  env: Env,
  question: string,
  briefing: CitedBriefing,
): Promise<string> {
  const id = newBriefingId();
  const stored: StoredBriefing = { id, ts: Date.now(), question, briefing };
  await env.PREFS.put(KEY_PREFIX + id, JSON.stringify(stored), {
    expirationTtl: TTL_SECONDS,
  });
  return id;
}

export async function loadBriefing(env: Env, id: string): Promise<StoredBriefing | null> {
  if (!/^[a-z0-9]{1,16}$/.test(id)) return null;
  const raw = await env.PREFS.get(KEY_PREFIX + id, "json");
  return (raw as StoredBriefing) ?? null;
}

export function briefingHtml(stored: StoredBriefing): string {
  const { briefing, question, ts } = stored;
  const points = briefing.keyPoints
    .map((p) => `<li>${escapeHtml(p)}</li>`)
    .join("");
  const cites = briefing.citations
    .slice()
    .sort((a, b) => a.n - b.n)
    .map(
      (c) =>
        `<li><a href="${escapeAttr(c.url)}" target="_blank" rel="noopener noreferrer">[${c.n}] ${escapeHtml(c.title)}</a> <span class="host">${escapeHtml(safeHost(c.url))}</span></li>`,
    )
    .join("");
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta property="og:title" content="${escapeAttr(briefing.topic)} — Clarity">
<meta property="og:description" content="${escapeAttr(briefing.summary.slice(0, 180))}">
<title>${escapeHtml(briefing.topic)} — Clarity</title>
<style>
  body { background: #0a0a0b; color: #e4e4e7; font-family: ui-sans-serif, system-ui, -apple-system, sans-serif; max-width: 720px; margin: 2rem auto; padding: 0 1.25rem; line-height: 1.6; }
  a { color: #fbad41; }
  h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
  .meta { color: #71717a; font-size: 0.85rem; margin-bottom: 1.5rem; }
  .question { background: #18181b; border-left: 3px solid #f6821f; padding: 0.75rem 1rem; border-radius: 4px; }
  ul { padding-left: 1.25rem; }
  li { margin: 0.4rem 0; }
  .host { color: #52525b; font-size: 0.85em; }
  .conf { display: inline-block; padding: 0.1rem 0.5rem; border-radius: 999px; font-size: 0.75rem; background: #18181b; color: #fbad41; border: 1px solid #3f3f46; }
  footer { margin-top: 2rem; color: #52525b; font-size: 0.8rem; }
</style>
</head><body>
<h1>${escapeHtml(briefing.topic)}</h1>
<div class="meta">
  <span class="conf">confidence: ${escapeHtml(briefing.confidence)}</span>
  · <time>${new Date(ts).toLocaleString()}</time>
</div>
<div class="question"><strong>Question:</strong> ${escapeHtml(question)}</div>
<p>${escapeHtml(briefing.summary)}</p>
<h2>Key points</h2>
<ul>${points}</ul>
<h2>Sources</h2>
<ul>${cites}</ul>
<footer>generated by <a href="/">cf_ai_clarity</a> · llama 3.3 on workers ai · cloudflare workflows</footer>
</body></html>`;
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (ch) =>
    ch === "&" ? "&amp;" : ch === "<" ? "&lt;" : ch === ">" ? "&gt;" : ch === '"' ? "&quot;" : "&#39;",
  );
}
function escapeAttr(s: string): string {
  return escapeHtml(s);
}
function safeHost(url: string): string {
  try {
    return new URL(url).hostname;
  } catch {
    return "";
  }
}
